version: "3.9"
   
services:
  web:
    build: .
    container_name: django-web-container
    volumes:
      - ../:/sr_project_stuff
      - ../DBs:/sr_project_stuff/DBs
      - ../logs:/sr_project_stuff/logs
      - .:/sr_project_stuff/code
    ports:
      - "8000:8000"

    environment:
      - FOO_KEY=bar_val
      - RES_FILES__ENV_SETTINGS_PATH=config/settings_localdev_env.sh

    env_file: ./config/settings_localdev_env.sh

    command: /bin/bash -c "python manage.py runserver 0.0.0.0:8000"
